---
- name: "Check for binary"
  ansible.builtin.stat:
    path: "{{ consul_exporter_install_dir }}/{{ consul_exporter_bin_name }}"
  changed_when: false
  register: __installed_bin

- name: "Create user"
  ansible.builtin.include_tasks: create_user.yml
  when: consul_exporter_user != "root"

- name: "Sources install tasks"
  ansible.builtin.include_tasks: install_src.yml
  when: consul_exporter_install_method == "src"

- name: "Configuring systemd"
  ansible.builtin.template:
    src: consul_exporter.service.j2
    dest: "/etc/systemd/system/consul_exporter.service"
    owner: root
    group: root
    mode: "0644"
  notify: "Restart consul_exporter"
  register: __config_systemd

- name: "Start service"
  ansible.builtin.service:
    name: consul_exporter
    state: started
    enabled: true
    daemon_reload: true
  when:
    - consul_exporter_start_service
    - __config_systemd.changed
