---
- name: "Check for consul_exporter binary"
  ansible.builtin.stat:
    path: '{{ consul_exporter_install_dir }}/consul_exporter'
  changed_when: false
  register: consul_exporter_install

- name: "Install tasks"
  when: not consul_exporter_install.stat.exists or consul_exporter_force_install|bool
  block:
    - name: "Install requierements"
      ansible.builtin.package:
        name: ["ca-certificates", "unzip", "tar"]
        state: present

    - name: "Download consul_exporter..."
      ansible.builtin.get_url:
        url: '{{ consul_exporter_tgz_url }}'
        dest: '{{ consul_exporter_temp_dir }}/{{ consul_exporter_tgz }}'
        timeout: '60'
        mode: '0644'

    - name: "Ensure install dir exists"
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      with_items:
        - '{{ consul_exporter_install_dir }}'
        - '{{ consul_exporter_temp_dir }}/consul_exporter'

    - name: "Unarchive consul_exporter..."
      ansible.builtin.unarchive:
        src: '{{ consul_exporter_temp_dir }}/{{ consul_exporter_tgz }}'
        dest: '{{ consul_exporter_temp_dir }}/consul_exporter'
        extra_opts: [--strip-components=1]
        remote_src: true
        mode: '0644'

    - name: "Copy consul_exporter binary..."
      ansible.builtin.copy:
        src: '{{ consul_exporter_temp_dir }}/consul_exporter/consul_exporter'
        dest: '{{ consul_exporter_install_dir }}/consul_exporter'
        remote_src: true
        mode: '0755'

    - name: "Remove temporary directory"
      ansible.builtin.file:
        path: '{{ consul_exporter_temp_dir }}/consul_exporter'
        state: absent

- name: "Create systemd for consul_exporter"
  ansible.builtin.template:
    src: 'consul_exporter.service.j2'
    dest: '/etc/systemd/system/consul_exporter.service'
    mode: '0640'
  notify: "Restart consul_exporter"

- name: "Start consul_exporter.service"
  ansible.builtin.service:
    name: consul_exporter
    state: started
    enabled: true
    daemon_reload: true
