---
- name: "Check for binary"
  ansible.builtin.stat:
    path: "{{ consul_exporter_install_dir }}/{{ consul_exporter_bin_name }}"
  changed_when: false
  register: __installed_bin

- name: "Sources install tasks"
  ansible.builtin.include_tasks: install_src.yml
  when: consul_exporter_install_method == "src"

- name: "Configuring systemd"
  ansible.builtin.template:
    src: consul_exporter.service.j2
    dest: "/lib/systemd/system/consul_exporter.service"
    owner: "{{ consul_exporter_user }}"
    group: "{{ consul_exporter_group }}"
    mode: "0644"
  notify: "Restart consul_exporter"

- name: "Start service"
  ansible.builtin.service:
    name: consul_exporter
    state: started
    enabled: true
    daemon_reload: true
  when: consul_exporter_start_service
